# syntax=docker/dockerfile:1

FROM golang:1.25 AS builder

RUN CGO_ENABLED=0 go install github.com/pressly/goose/v3/cmd/goose@v3.27.3

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /go/bin/goose /usr/local/bin/goose
COPY internal/db/migrations /migrations

ENTRYPOINT ["goose"]
